include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # 👇 vypneme kosmetické věci (teď tě jen brzdí)
    avoid_print: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    use_super_parameters: ignore

linter:
  rules:
    # 👇 tohle necháváme zapnuté (důležité bugy)
    use_build_context_synchronously: true