// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4N0-YwjZGUHYM3oAklj_CPbcWuQ3gDo0',
    appId: '1:975656862720:android:0829f526683ef9fce084e5',
    messagingSenderId: '975656862720',
    projectId: 'fitness-app-spal',
    storageBucket: 'fitness-app-spal.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMN38L8zs10Sl1NEd6a9Mt93FUQgX6YVA',
    appId: '1:975656862720:web:b2a154b511d98291e084e5',
    messagingSenderId: '975656862720',
    projectId: 'fitness-app-spal',
    authDomain: 'fitness-app-spal.firebaseapp.com',
    storageBucket: 'fitness-app-spal.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMN38L8zs10Sl1NEd6a9Mt93FUQgX6YVA',
    appId: '1:975656862720:web:b2a154b511d98291e084e5',
    messagingSenderId: '975656862720',
    projectId: 'fitness-app-spal',
    authDomain: 'fitness-app-spal.firebaseapp.com',
    storageBucket: 'fitness-app-spal.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKOnznYtv415uP5V1JAmUZRZC-soxwzE4',
    appId: '1:975656862720:ios:27885310c8d69214e084e5',
    messagingSenderId: '975656862720',
    projectId: 'fitness-app-spal',
    storageBucket: 'fitness-app-spal.firebasestorage.app',
    iosBundleId: 'com.example.dartApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOnznYtv415uP5V1JAmUZRZC-soxwzE4',
    appId: '1:975656862720:ios:27885310c8d69214e084e5',
    messagingSenderId: '975656862720',
    projectId: 'fitness-app-spal',
    storageBucket: 'fitness-app-spal.firebasestorage.app',
    iosBundleId: 'com.example.dartApplication1',
  );

}