import 'exercise.dart';

class ExerciseIds {
  // Big 3
  static const squat = 'squat';
  static const bench = 'bench_press';
  static const deadlift = 'deadlift';

  // Variations
  static const pauseSquat = 'pause_squat';
  static const tempoSquat = 'tempo_squat';
  static const frontSquat = 'front_squat';

  static const closeGripBench = 'close_grip_bench';
  static const dbBench = 'db_bench';
  static const pauseBench = 'pause_bench';

  static const inclineDbPress = 'incline_db_press';
  static const chestPressMachine = 'chest_press_machine';
  static const declineBench = 'decline_bench';
  static const dipsChest = 'dips_chest';
  static const widePushUp = 'wide_push_up';

  static const dbFly = 'db_fly';
  static const cableFly = 'cable_fly';
  static const peckDeck = 'peck_deck';
  static const pullover = 'pullover';

  static const rdl = 'rdl';
  static const blockPull = 'block_pull';
  static const rackPull = 'rack_pull';
  static const hyperextension = 'hyperextension';

  // Back
  static const barbellRow = 'barbell_row';
  static const oneArmDbRow = 'one_arm_db_row';
  static const seatedCableRow = 'seated_cable_row';
  static const tBarRow = 'tbar_row';
  static const sealRow = 'seal_row';

  static const pullUps = 'pull_ups';
  static const assistedPullUps = 'assisted_pull_ups';
  static const latPulldown = 'lat_pulldown';
  static const straightArmPulldown = 'straight_arm_pulldown';

  // Shoulders
  static const overheadPress = 'overhead_press';
  static const dbShoulderPress = 'db_shoulder_press';
  static const arnoldPress = 'arnold_press';
  static const lateralRaise = 'lateral_raise';
  static const cableLateralRaise = 'cable_lateral_raise';
  static const lateralRaiseMachine = 'lateral_raise_machine';
  static const uprightRowWide = 'upright_row_wide';
  static const facePull = 'face_pull';
  static const reversePeckDeck = 'reverse_peck_deck';
  static const rearDeltFly = 'rear_delt_fly';
  static const cableRearDeltFly = 'cable_rear_delt_fly';
  static const shrugs = 'shrugs';

  // Triceps
  static const tricepsPushdown = 'triceps_pushdown';
  static const dipsTriceps = 'dips_triceps';
  static const skullcrusher = 'skullcrusher';
  static const overheadTricepsExtension = 'overhead_triceps_extension';
  static const kickback = 'kickback';

  // Biceps
  static const bicepsCurl = 'biceps_curl';
  static const ezBarCurl = 'ez_bar_curl';
  static const dbCurl = 'db_curl';
  static const hammerCurl = 'hammer_curl';
  static const preacherCurl = 'preacher_curl';
  static const concentrationCurl = 'concentration_curl';
  static const reverseCurl = 'reverse_curl';

  // Legs
  static const hamstringCurl = 'hamstring_curl';
  static const legPress = 'leg_press';
  static const splitSquat = 'split_squat';
  static const hackSquat = 'hack_squat';
  static const legExtension = 'leg_extension';
  static const stiffLegDeadlift = 'stiff_leg_deadlift';
  static const gluteHamRaise = 'glute_ham_raise';
  static const hipThrust = 'hip_thrust';
  static const bulgarianSplitSquat = 'bulgarian_split_squat';
  static const gluteKickback = 'glute_kickback';
  static const abductionMachine = 'abduction_machine';
  static const sumoSquat = 'sumo_squat';

  // Core / mobility
  static const core = 'core';
  static const mobility = 'mobility';
  static const plank = 'plank';
  static const hangingLegRaise = 'hanging_leg_raise';
  static const cableCrunch = 'cable_crunch';
  static const russianTwist = 'russian_twist';
  static const abWheel = 'ab_wheel';
  static const sidePlank = 'side_plank';

  // Endurance / conditioning
  static const run = 'run';
  static const bike = 'bike';
  static const rower = 'rower';
}

class ExerciseDB {
  static const List<Exercise> all = [
    // =========================
    // Strength - Big 3
    // =========================
    Exercise(
      id: ExerciseIds.squat,
      name: 'Back Squat',
      czName: 'Dřep s velkou činkou na zádech',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'rack'},
      primaryMuscles: ['quads', 'glutes'],
      substitutions: [ExerciseIds.frontSquat, ExerciseIds.tempoSquat, ExerciseIds.pauseSquat],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.bench,
      name: 'Bench Press',
      czName: 'Bench press (tlaky na prsa na rovné lavici)',
      pattern: MovementPattern.press,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'bench'},
      primaryMuscles: ['chest', 'triceps', 'front_delts'],
      substitutions: [ExerciseIds.closeGripBench, ExerciseIds.dbBench, ExerciseIds.pauseBench],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.deadlift,
      name: 'Deadlift',
      czName: 'Mrtvý tah',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.strength,
      equipment: {'barbell'},
      primaryMuscles: ['hamstrings', 'glutes', 'back'],
      substitutions: [ExerciseIds.rdl, ExerciseIds.blockPull, ExerciseIds.rackPull],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Squat / bench variations
    // =========================
    Exercise(
      id: ExerciseIds.pauseSquat,
      name: 'Pause Squat',
      czName: 'Dřep s pauzou',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'rack'},
      primaryMuscles: ['quads', 'glutes'],
      substitutions: [ExerciseIds.squat, ExerciseIds.frontSquat],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.tempoSquat,
      name: 'Tempo Squat',
      czName: 'Tempo dřep',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell', 'rack'},
      primaryMuscles: ['quads', 'glutes'],
      substitutions: [ExerciseIds.squat, ExerciseIds.frontSquat],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.frontSquat,
      name: 'Front Squat',
      czName: 'Čelní dřep',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'rack'},
      primaryMuscles: ['quads', 'core'],
      substitutions: [ExerciseIds.squat, ExerciseIds.pauseSquat],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.closeGripBench,
      name: 'Close Grip Bench Press',
      czName: 'Tlaky na úzko s velkou činkou',
      pattern: MovementPattern.press,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'bench'},
      primaryMuscles: ['triceps', 'chest'],
      substitutions: [ExerciseIds.bench, ExerciseIds.dbBench],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.dbBench,
      name: 'Dumbbell Bench Press',
      czName: 'Tlaky s jednoručkami na rovné lavici',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench'},
      primaryMuscles: ['chest', 'triceps'],
      substitutions: [ExerciseIds.bench, ExerciseIds.closeGripBench],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.pauseBench,
      name: 'Pause Bench Press',
      czName: 'Bench press s pauzou',
      pattern: MovementPattern.press,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'bench'},
      primaryMuscles: ['chest', 'triceps'],
      substitutions: [ExerciseIds.bench, ExerciseIds.closeGripBench],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.inclineDbPress,
      name: 'Incline Dumbbell Press',
      czName: 'Tlaky s jednoručkami na šikmé lavici',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench'},
      primaryMuscles: ['chest', 'front_delts', 'triceps'],
      substitutions: [ExerciseIds.dbBench, ExerciseIds.bench],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.chestPressMachine,
      name: 'Chest Press Machine',
      czName: 'Tlaky na stroji (chest press)',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['chest', 'triceps'],
      substitutions: [ExerciseIds.dbBench],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.declineBench,
      name: 'Decline Bench Press',
      czName: 'Bench press hlavou dolů',
      pattern: MovementPattern.press,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'bench'},
      primaryMuscles: ['chest', 'triceps'],
      substitutions: [ExerciseIds.bench],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.dipsChest,
      name: 'Chest Dips',
      czName: 'Kliky na bradlech s předklonem (na prsa)',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'bodyweight'},
      primaryMuscles: ['chest', 'triceps'],
      substitutions: [ExerciseIds.widePushUp],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.widePushUp,
      name: 'Wide Push-Up',
      czName: 'Kliky se širokým úchopem',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'bodyweight'},
      primaryMuscles: ['chest', 'triceps'],
      substitutions: [ExerciseIds.dipsChest],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.dbFly,
      name: 'Dumbbell Fly',
      czName: 'Rozpažování s jednoručkami',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench'},
      primaryMuscles: ['chest'],
      substitutions: [ExerciseIds.cableFly, ExerciseIds.peckDeck],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.cableFly,
      name: 'Cable Fly',
      czName: 'Stahování protisměrných kladek',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['chest'],
      substitutions: [ExerciseIds.dbFly, ExerciseIds.peckDeck],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.peckDeck,
      name: 'Peck Deck',
      czName: 'Peck-deck (stroj na rozpažování)',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['chest'],
      substitutions: [ExerciseIds.dbFly, ExerciseIds.cableFly],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.pullover,
      name: 'Dumbbell Pullover',
      czName: 'Pullover s jednoručkou',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench'},
      primaryMuscles: ['chest', 'back'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Hinge / lower back
    // =========================
    Exercise(
      id: ExerciseIds.rdl,
      name: 'Romanian Deadlift',
      czName: 'Rumunský mrtvý tah',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell'},
      primaryMuscles: ['hamstrings', 'glutes'],
      substitutions: [ExerciseIds.deadlift, ExerciseIds.stiffLegDeadlift],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.blockPull,
      name: 'Block Pull',
      czName: 'Mrtvý tah z podložky',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.strength,
      equipment: {'barbell'},
      primaryMuscles: ['back', 'glutes'],
      substitutions: [ExerciseIds.deadlift, ExerciseIds.rackPull],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.rackPull,
      name: 'Rack Pull',
      czName: 'Rack pull (mrtvý tah ze zarážek)',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.strength,
      equipment: {'barbell', 'rack'},
      primaryMuscles: ['back', 'glutes', 'hamstrings'],
      substitutions: [ExerciseIds.blockPull, ExerciseIds.deadlift],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.hyperextension,
      name: 'Hyperextension',
      czName: 'Hyperextenze',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.hypertrophy,
      equipment: {'bodyweight'},
      primaryMuscles: ['back', 'glutes', 'hamstrings'],
      substitutions: [],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Back
    // =========================
    Exercise(
      id: ExerciseIds.barbellRow,
      name: 'Barbell Row',
      czName: 'Přítahy velké činky v předklonu',
      pattern: MovementPattern.row,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.oneArmDbRow, ExerciseIds.seatedCableRow],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.oneArmDbRow,
      name: 'One Arm Dumbbell Row',
      czName: 'Přítahy jednoručky v předklonu',
      pattern: MovementPattern.row,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.barbellRow, ExerciseIds.seatedCableRow],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.seatedCableRow,
      name: 'Seated Cable Row',
      czName: 'Přítahy na spodní kladce v sedě',
      pattern: MovementPattern.row,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.barbellRow],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.tBarRow,
      name: 'T-Bar Row',
      czName: 'Přítahy T-osy',
      pattern: MovementPattern.row,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.barbellRow],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.sealRow,
      name: 'Seal Row',
      czName: 'Seal row (přítahy vleže na lavici)',
      pattern: MovementPattern.row,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell', 'bench'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.barbellRow],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.pullUps,
      name: 'Pull-Ups',
      czName: 'Shyby na hrazdě',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'bodyweight'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.latPulldown, ExerciseIds.assistedPullUps],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.assistedPullUps,
      name: 'Assisted Pull-Ups',
      czName: 'Shyby s dopomocí',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.pullUps, ExerciseIds.latPulldown],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.latPulldown,
      name: 'Lat Pulldown',
      czName: 'Stahování horní kladky k hrudníku',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['back', 'biceps'],
      substitutions: [ExerciseIds.pullUps, ExerciseIds.assistedPullUps],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.straightArmPulldown,
      name: 'Straight Arm Pulldown',
      czName: 'Stahování horní kladky s nataženými pažemi',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['back'],
      substitutions: [ExerciseIds.latPulldown],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Shoulders
    // =========================
    Exercise(
      id: ExerciseIds.overheadPress,
      name: 'Military Press',
      czName: 'Military press (tlak nad hlavu)',
      pattern: MovementPattern.press,
      modality: ExerciseModality.strength,
      equipment: {'barbell'},
      primaryMuscles: ['delts', 'triceps', 'front_delts'],
      substitutions: [ExerciseIds.dbShoulderPress, ExerciseIds.arnoldPress],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.dbShoulderPress,
      name: 'Dumbbell Shoulder Press',
      czName: 'Tlaky s jednoručkami na ramena',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench'},
      primaryMuscles: ['delts', 'front_delts', 'triceps'],
      substitutions: [ExerciseIds.overheadPress],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.arnoldPress,
      name: 'Arnold Press',
      czName: 'Arnoldovy tlaky',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench'},
      primaryMuscles: ['delts', 'front_delts'],
      substitutions: [ExerciseIds.dbShoulderPress],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.lateralRaise,
      name: 'Lateral Raise',
      czName: 'Upažování s jednoručkami',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell'},
      primaryMuscles: ['delts'],
      substitutions: [ExerciseIds.cableLateralRaise, ExerciseIds.lateralRaiseMachine],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.cableLateralRaise,
      name: 'Cable Lateral Raise',
      czName: 'Upažování s kladkou za tělem',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['delts'],
      substitutions: [ExerciseIds.lateralRaise],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.lateralRaiseMachine,
      name: 'Lateral Raise Machine',
      czName: 'Upažování na stroji',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['delts'],
      substitutions: [ExerciseIds.lateralRaise],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.uprightRowWide,
      name: 'Wide Upright Row',
      czName: 'Přítahy osy k bradě širokým úchopem',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell'},
      primaryMuscles: ['delts', 'traps'],
      substitutions: [ExerciseIds.lateralRaise],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.facePull,
      name: 'Face Pull',
      czName: 'Face pulls (tah lana k obličeji)',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['rear_delts', 'traps'],
      substitutions: [ExerciseIds.reversePeckDeck, ExerciseIds.rearDeltFly],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.reversePeckDeck,
      name: 'Reverse Peck Deck',
      czName: 'Obrácený peck-deck',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['rear_delts'],
      substitutions: [ExerciseIds.facePull],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.rearDeltFly,
      name: 'Rear Delt Fly',
      czName: 'Upažování v předklonu',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell'},
      primaryMuscles: ['rear_delts'],
      substitutions: [ExerciseIds.reversePeckDeck],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.cableRearDeltFly,
      name: 'Cable Rear Delt Fly',
      czName: 'Zapažování na protisměrných kladkách',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['rear_delts'],
      substitutions: [ExerciseIds.rearDeltFly],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.shrugs,
      name: 'Shrugs',
      czName: 'Krčení ramen s činkami',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'barbell'},
      primaryMuscles: ['traps'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Triceps
    // =========================
    Exercise(
      id: ExerciseIds.tricepsPushdown,
      name: 'Triceps Pushdown',
      czName: 'Stahování horní kladky s lanem',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['triceps'],
      substitutions: [ExerciseIds.overheadTricepsExtension],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.dipsTriceps,
      name: 'Triceps Dips',
      czName: 'Kliky na bradlech na triceps',
      pattern: MovementPattern.press,
      modality: ExerciseModality.strength,
      equipment: {'bodyweight'},
      primaryMuscles: ['triceps'],
      substitutions: [ExerciseIds.closeGripBench],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.skullcrusher,
      name: 'Skullcrusher',
      czName: 'Francouzský tlak',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell', 'dumbbell', 'bench'},
      primaryMuscles: ['triceps'],
      substitutions: [ExerciseIds.tricepsPushdown],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.overheadTricepsExtension,
      name: 'Overhead Triceps Extension',
      czName: 'Tricepsové extenze nad hlavou',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'machine'},
      primaryMuscles: ['triceps'],
      substitutions: [ExerciseIds.tricepsPushdown],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.kickback,
      name: 'Triceps Kickback',
      czName: 'Kick-back na triceps',
      pattern: MovementPattern.press,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'machine'},
      primaryMuscles: ['triceps'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Biceps
    // =========================
    Exercise(
      id: ExerciseIds.bicepsCurl,
      name: 'Biceps Curl',
      czName: 'Bicepsový zdvih',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'barbell'},
      primaryMuscles: ['biceps'],
      substitutions: [ExerciseIds.dbCurl, ExerciseIds.ezBarCurl],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.ezBarCurl,
      name: 'EZ Bar Curl',
      czName: 'Bicepsový zdvih s EZ osou',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell'},
      primaryMuscles: ['biceps'],
      substitutions: [ExerciseIds.dbCurl],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.dbCurl,
      name: 'Dumbbell Curl',
      czName: 'Bicepsový zdvih s jednoručkami s rotací',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell'},
      primaryMuscles: ['biceps'],
      substitutions: [ExerciseIds.ezBarCurl],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.hammerCurl,
      name: 'Hammer Curl',
      czName: 'Kladivové zdvihy',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell'},
      primaryMuscles: ['biceps', 'brachialis', 'forearms'],
      substitutions: [ExerciseIds.dbCurl],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.preacherCurl,
      name: 'Preacher Curl',
      czName: 'Scottova lavice',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell', 'dumbbell', 'bench'},
      primaryMuscles: ['biceps'],
      substitutions: [ExerciseIds.dbCurl],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.concentrationCurl,
      name: 'Concentration Curl',
      czName: 'Koncentrovaný zdvih o koleno',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell'},
      primaryMuscles: ['biceps'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.reverseCurl,
      name: 'Reverse Curl',
      czName: 'Zdvihy s nadhmatem',
      pattern: MovementPattern.pull,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell', 'dumbbell'},
      primaryMuscles: ['forearms', 'biceps'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Legs
    // =========================
    Exercise(
      id: ExerciseIds.hamstringCurl,
      name: 'Hamstring Curl',
      czName: 'Zakopávání',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['hamstrings'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.legPress,
      name: 'Leg Press',
      czName: 'Leg press',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['quads', 'glutes'],
      substitutions: [ExerciseIds.squat, ExerciseIds.hackSquat],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.splitSquat,
      name: 'Split Squat',
      czName: 'Výpady / split squat',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bodyweight'},
      primaryMuscles: ['quads', 'glutes'],
      substitutions: [ExerciseIds.legPress],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.hackSquat,
      name: 'Hack Squat',
      czName: 'Hack-dřep',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['quads'],
      substitutions: [ExerciseIds.legPress],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.legExtension,
      name: 'Leg Extension',
      czName: 'Předkopávání na stroji',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['quads'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.stiffLegDeadlift,
      name: 'Stiff Leg Deadlift',
      czName: 'Mrtvý tah s nataženýma nohama',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell'},
      primaryMuscles: ['hamstrings'],
      substitutions: [ExerciseIds.rdl],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.gluteHamRaise,
      name: 'Glute Ham Raise',
      czName: 'Glute-ham raise',
      pattern: MovementPattern.hinge,
      modality: ExerciseModality.hypertrophy,
      equipment: {'bodyweight'},
      primaryMuscles: ['hamstrings', 'glutes'],
      substitutions: [ExerciseIds.hamstringCurl],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.hipThrust,
      name: 'Hip Thrust',
      czName: 'Hip thrust (zdvih pánve se zátěží)',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell', 'bench'},
      primaryMuscles: ['glutes'],
      substitutions: [ExerciseIds.gluteKickback],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.bulgarianSplitSquat,
      name: 'Bulgarian Split Squat',
      czName: 'Bulharské dřepy',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'dumbbell', 'bench', 'bodyweight'},
      primaryMuscles: ['glutes', 'quads'],
      substitutions: [ExerciseIds.splitSquat],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.gluteKickback,
      name: 'Glute Kickback',
      czName: 'Zanožování na kladce',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['glutes'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.abductionMachine,
      name: 'Abduction Machine',
      czName: 'Abdukce na stroji',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'machine'},
      primaryMuscles: ['glutes'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.sumoSquat,
      name: 'Sumo Squat',
      czName: 'Hluboký dřep se širokým postojem',
      pattern: MovementPattern.squat,
      modality: ExerciseModality.hypertrophy,
      equipment: {'barbell', 'dumbbell'},
      primaryMuscles: ['glutes', 'quads'],
      substitutions: [],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),

    // =========================
    // Core / mobility
    // =========================
    Exercise(
      id: ExerciseIds.core,
      name: 'Core',
      czName: 'Střed těla',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'bodyweight'},
      primaryMuscles: ['core'],
      substitutions: [ExerciseIds.plank, ExerciseIds.sidePlank],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: true,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.mobility,
      name: 'Mobility',
      czName: 'Mobilita',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'bodyweight'},
      primaryMuscles: ['mobility'],
      substitutions: [],
      supportsLoadKg: false,
      supportsReps: false,
      supportsDuration: true,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.plank,
      name: 'Plank',
      czName: 'Plank (prkno)',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'bodyweight'},
      primaryMuscles: ['core'],
      substitutions: [ExerciseIds.sidePlank],
      supportsLoadKg: false,
      supportsReps: false,
      supportsDuration: true,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.hangingLegRaise,
      name: 'Hanging Leg Raise',
      czName: 'Zvedání nohou ve visu',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'bodyweight'},
      primaryMuscles: ['core'],
      substitutions: [ExerciseIds.cableCrunch],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.cableCrunch,
      name: 'Cable Crunch',
      czName: 'Zkracovačky na horní kladce',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'machine'},
      primaryMuscles: ['core'],
      substitutions: [ExerciseIds.hangingLegRaise],
      supportsLoadKg: true,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.russianTwist,
      name: 'Russian Twist',
      czName: 'Ruský twist',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'bodyweight', 'dumbbell'},
      primaryMuscles: ['core'],
      substitutions: [],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.abWheel,
      name: 'Ab Wheel Rollout',
      czName: 'Ab-wheel rollout',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'bodyweight'},
      primaryMuscles: ['core'],
      substitutions: [],
      supportsLoadKg: false,
      supportsReps: true,
      supportsDuration: false,
      supportsDistance: false,
    ),
    Exercise(
      id: ExerciseIds.sidePlank,
      name: 'Side Plank',
      czName: 'Vzpor na boku',
      pattern: MovementPattern.core,
      modality: ExerciseModality.conditioning,
      equipment: {'bodyweight'},
      primaryMuscles: ['core'],
      substitutions: [ExerciseIds.plank],
      supportsLoadKg: false,
      supportsReps: false,
      supportsDuration: true,
      supportsDistance: false,
    ),

    // =========================
    // Endurance / conditioning
    // =========================
    Exercise(
      id: ExerciseIds.run,
      name: 'Run',
      czName: 'Běh',
      pattern: MovementPattern.locomotion,
      modality: ExerciseModality.endurance,
      equipment: {'cardio'},
      primaryMuscles: ['legs', 'cardio'],
      substitutions: [ExerciseIds.bike, ExerciseIds.rower],
      supportsLoadKg: false,
      supportsReps: false,
      supportsDuration: true,
      supportsDistance: true,
    ),
    Exercise(
      id: ExerciseIds.bike,
      name: 'Bike',
      czName: 'Kolo',
      pattern: MovementPattern.locomotion,
      modality: ExerciseModality.endurance,
      equipment: {'cardio'},
      primaryMuscles: ['legs', 'cardio'],
      substitutions: [ExerciseIds.run, ExerciseIds.rower],
      supportsLoadKg: false,
      supportsReps: false,
      supportsDuration: true,
      supportsDistance: true,
    ),
    Exercise(
      id: ExerciseIds.rower,
      name: 'Rower',
      czName: 'Veslo (ergometr)',
      pattern: MovementPattern.locomotion,
      modality: ExerciseModality.endurance,
      equipment: {'cardio'},
      primaryMuscles: ['back', 'legs', 'cardio'],
      substitutions: [ExerciseIds.bike, ExerciseIds.run],
      supportsLoadKg: false,
      supportsReps: false,
      supportsDuration: true,
      supportsDistance: true,
    ),
  ];
}